import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import React, { useContext } from 'react';
import { toast } from 'react-hot-toast';
import { AuthContext } from '../../contexts/AuthProvider';

const Login = () => {
  const { loginExistedUser, googleSignUp, loading, setLoading } = useContext(AuthContext);
  const router = useRouter();
  // login handle
  const handleLogin = (e) => {
    e.preventDefault();
    const form = e.target;
    const email = form.email.value;
    const password = form.password.value;
    loginExistedUser(email, password)
      .then((result) => {
        const { user } = result;
        console.log(user);
        form.reset();
        router.push('/');
        toast.success("User Login Successfully");
      }).catch((err) => {
        console.error(err);
        toast.error(err.message);
      })
  }

  // google login
  const handleGoogleLogin = () => {
    googleSignUp()
      .then((result) => {
        const { user } = result.user;
        router.push('/');
        toast.success("Google sign up successful");
      }).catch((err) => {
        console.error(err);
        toast.error(err.message);
      })
  }

  return (
    <>
      <Head>
        <title>Login - Next Firebase</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="w-full md:w-1/3 mx-auto mt-20 flex justify-center items-center">
        <div className="flex-1">
          <div>
            <h2 className="text-3xl font-semibold">Login</h2>
          </div>
          <div className="my-4">
            <div>
              <form onSubmit={handleLogin} className="space-y-2">
                <div>
                  <input className="w-full rounded-md" type="email" name="email" placeholder="Email" />
                </div>
                <div className="w-full">
                  <input className="w-full rounded-md" type="password" name="password" placeholder="Password" />
                </div>
                <div>
                  <button type="submit" className="bg-sky-500 w-full py-2 flex gap-2 justify-center items-center font-bold text-white rounded-md">
                    <span>Login</span>
                    <span>
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M17.25 8.25L21 12m0 0l-3.75 3.75M21 12H3" />
                      </svg>
                    </span>
                  </button>
                </div>
              </form>
            </div>
          </div>
          <div>
            <button onClick={handleGoogleLogin} className="border-2 border-sky-100 text-gray-600 w-full py-2 font-bold hover:bg-sky-100 rounded-md">Login with Google</button>
            <p className="text-center mt-1">Does not have any account?
              <Link className="text-sky-600 font-medium hover:underline" href="/register">Register</Link>
            </p>
          </div>
        </div>
      </section>
    </>
  );
};

export default Login;