import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useContext } from 'react';
import { toast } from 'react-hot-toast';
import { AuthContext } from '../../contexts/AuthProvider';
import { addTaskToDb } from '../../taskApi/taskApi';

const AddTask = () => {
  const { user } = useContext(AuthContext);
  const router = useRouter();
  const handleAddTask = (e) => {
    e.preventDefault();
    const form = e.target;
    const title = form.title.value;
    const description = form.description.value;
    const taskData = {
      title,
      description,
      userEmail: user?.email,
      addedTime: new Date().toLocaleString(),
      status: 'incomplete'
    };
    // api
    addTaskToDb(taskData)
      .then((data) => {
        if (data.acknowledged) {
          form.reset();
          console.log(data);
          toast.success("Task Added");
          router.push('/myTask')
        }
      }).catch((error) => {
        console.log(err);
        toast.error(err.message);
      })
  }

  return (
    <>
      <Head>
        <title>Add Task - Next Firebase</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="md:w-1/2 mx-auto">
        <div>
          <h2 className="text-2xl font-semibold">Add Task</h2>
        </div>
        <div className="mt-2">
          <form onSubmit={handleAddTask} className="space-y-2">
            <div>
              <input name="title" type="text" className="w-full rounded-md border-2 border-sky-600 focus:border-sky-300" placeholder="Task Title Here" />
            </div>
            <div>
              <textarea name="description" cols="30" rows="5" className="w-full rounded-md border-2 border-sky-600 focus:border-sky-300" placeholder="Task Description Here"></textarea>
            </div>
            <div>
              <button type="submit" className="bg-sky-500 w-full py-2 text-white rounded-md font-bold">
                Submit
              </button>
            </div>
          </form>
        </div>
      </section>
    </>
  );
};

export default AddTask;