import Head from 'next/head';
import React, { useContext } from 'react';
import useSWR from 'swr'
import MyTask from '../../components/MyTask/MyTask';
import { AuthContext } from '../../contexts/AuthProvider';

const fetcher = (...args) => fetch(...args).then(res => res.json())

const MyTasks = () => {
  const { user } = useContext(AuthContext);
  const { data: tasks, isLoading, error, mutate } = useSWR(`${process.env.NEXT_PUBLIC_API_URL}/user/tasks/${user?.email}?status=incomplete`, fetcher);
  return (
    <>
      <Head>
        <title>My Task - Next Firebase</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="md:w-1/2 mx-auto">
        <div>
          <h2 className="text-2xl font-semibold">My Task</h2>
        </div>
        <div>
          {
            tasks?.length !== 0 ?
              <>
                {
                  tasks?.map(task => <MyTask
                    key={task._id}
                    task={task}
                  ></MyTask>)
                }
              </>
              :
              <>
                <div className="mt-2">
                <h2 className="text-sky-600 font-bold">You do not have any added tasks.</h2>
                </div>
              </>
          }
        </div>
      </section>
    </>
  );
};

export default MyTasks;
