import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Next Firebase</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="h-screen flex justify-center items-center">
          <h2 className="text-2xl font-semibold">Hello Next.js Firebase Project</h2>
        </div>
      </main>
    </>
  )
}
